### ISSUE TITLE
训练程序不支持断点训练

### ISSUE THREAD

**Issue by licongguan** [BIT-DA/RIPU#1]
if cfg.resume:  训练时加上resume 以及模型，程序还是从头开始训练

**Comment by BinhuiXie** [comment]
Hi @licongguan，

Sorry about it. Here, `cfg.resume` is only used to load checkpoint (specifically load model parameters). If you want to resume the whole process, iteration and optimizers should be loaded and modify some lines accordingly.

**Comment by BinhuiXie** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.

**Comment by licongguan** [comment]
Hi, I get it, but it would be better if you could keep optimizing your code so it can apply reverting the whole process, iteration and optimizer.
