### ISSUE TITLE
Is it possible to apply this method to medical image segmentation?

### ISSUE THREAD

**Issue by 02zp11** [BIT-DA/RIPU#5]
Can domain adaptive semantic segmentation mentioned in this paper be applied to medical image segmentation?

**Comment by BinhuiXie** [comment]
Hi @zhouping11 

Thank you for being so interested. It is possible to apply our selection strategy to medical image segmentation. 

BTW, we released a recent work that used a similar idea to establish a baseline for LiDAR semantic segmentation.

Project page: https://binhuixie.github.io/annotator-web/
Paper: https://arxiv.org/pdf/2310.20293.pdf
GitHub: https://github.com/BIT-DA/Annotator
